Reduced Subgraph Calls
yearn/yearn-watch-legacy pull request #173
Opened 2021-10-27 15:58 UTC by magikadev

2021-10-27 21:56 UTC, salazarguille requested changes
Hi MagicD990619, thank you very much for your job!!!

I left some comments.

Also, please could you check if the warning for the health check is working properly?

For example:

https://etherscan.io/address/0x1D371Ae86c8316917373Ec572B18776655Fd11b7#readContract

This strategy has `doHealthCheck` = true, and `healthCheck` = 0xddcea799ff1699e98edf118e0629a974df7df012

But the warning is displayed here `StrategGenLevAave`

![image](https://user-images.githubusercontent.com/5948309/139153023-f24b1474-4a96-4c66-9441-7fd6d1bcb7d6.png)

2021-10-27 21:56 UTC, salazarguille commented on src/utils/strategies.ts
> +        for (
Is it possible to implement it using _.join function to make it easy to read?

2021-10-27 21:56 UTC, salazarguille commented on src/utils/strategies.ts
> +            healthCheckResults.data.strategies.map((strategy) => {
Question

I think as we are pushing a new object into `healCheckInfos`, we don't need to use a `map` here. I think it would work with a `forEach`.

2021-10-28 17:56 UTC, storming0x commented
can we also test the healthcheck work in https://yearn.watch/network/fantom path as well @magic990619

2021-10-28 23:54 UTC, magikadev commented
I have fixed your comments, please check. @salazarguille 
![image](https://user-images.githubusercontent.com/46446076/139351607-350c09b6-5d4e-46b3-b9b0-be0360b7919f.png)

2021-10-29 14:47 UTC, salazarguille commented
> I have fixed your comments, please check. @salazarguille ![image](https://user-images.githubusercontent.com/46446076/139351607-350c09b6-5d4e-46b3-b9b0-be0360b7919f.png)

Thanks again!!

Question:

I still see that we are displaying `Do Next Health Check` = `disabled`.

But the strategy `doHealthCheck` is true.
![image](https://user-images.githubusercontent.com/5948309/139455437-aa973220-a37e-4d55-b3b8-8b48d5bc66c7.png)

The same for `GenLevCompV3`.

2021-10-29 16:51 UTC, salazarguille approved these changes
Great job @magic990619 LGTM!

2021-10-29 16:52 UTC, merged