upgrade react router dom
yearn/yearn-watch-legacy pull request #230
Opened 2022-02-20 15:36 UTC by laitanop

1.  Upgrading from "react-router-dom": "^5.2.0",   To  "react-router-dom": "^6.2.1"
2. Replaced from  "Switch " to "Routes"
3. Replaced from  "Redirect " to "Navigate"
4.  Replaced from component={} to  element={</>}
5. Replaced from  "useHistory " to "useNavigate"

2022-02-20 16:08 UTC, phillip055 requested changes
Other than that, LGTM

2022-02-20 16:08 UTC, phillip055 commented on src/App.tsx
> +                            element={Query}
does this need to be <Query /> too?

2022-02-21 13:17 UTC, magic990619 commented
@laitanop Would you please rebase with master branch?

2022-02-21 15:52 UTC, magic990619 commented
https://yearn-watch-a2667hw10-y-finance.vercel.app/network/ethereum/query
https://yearn-watch-a2667hw10-y-finance.vercel.app/network/ethereum/report
https://yearn-watch-a2667hw10-y-finance.vercel.app/network/ethereum/risk
The above routes are not working.

2022-02-22 13:33 UTC, merged