add tooltip on score
yearn/yearn-watch-legacy pull request #297
Opened 2022-04-01 14:02 UTC by CutupAngel

2022-04-01 21:00 UTC, rareweasel requested changes
It think some labels are not correct.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/89795397/161340564-195ed1d3-e66c-46dc-8933-1dd8048df159.png">


Source: https://yearn-watch-git-fork-cutupangel-102-add-tooltip-y-finance.vercel.app/network/arbitrum/risk

2022-04-01 21:58 UTC, CutupAngel commented
@rareweasel  I fixed this issue.
Please review again.

2022-04-04 15:52 UTC, rareweasel commented
Question: is it possible to increase the width size?

![image](https://user-images.githubusercontent.com/89795397/161583050-b867cd0b-6c90-4d25-a3ab-97f8284be675.png)

Then, LGTM

2022-04-04 21:58 UTC, rareweasel approved these changes

2022-04-04 22:58 UTC, magic990619 approved these changes

2022-04-04 22:59 UTC, merged